import {
  Hammer,
  Wrench,
  Paintbrush,
  Lightbulb,
  Thermometer,
  Droplet,
  BrickWall,
  Brush,
  Plug,
  Drill,
  HardHat,
  Ruler,
  Construction,
  ShieldCheck,
} from 'lucide-react'

export const iconList = {
  Hammer: <Hammer />,
  Wrench: <Wrench />,
  Paintbrush: <Paintbrush />,
  Lightbulb: <Lightbulb />,
  Thermometer: <Thermometer />,
  Droplet: <Droplet />,
  BrickWall: <BrickWall />,
  Brush: <Brush />,
  Plug: <Plug />,
  Drill: <Drill />,
  HardHat: <HardHat />,
  Ruler: <Ruler />,
  Construction: <Construction />,
  ShieldCheck: <ShieldCheck />,
}
